name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker pull
      run: |
        docker image pull katalonstudio/katalon:9.3.1
        mkdir /tmp/workspace

    - name: Katalon Run 1
      run:  |
        docker run -t --rm -v "$(pwd)":/tmp/project -v /tmp/workspace:/tmp/workspace katalonstudio/katalon:9.3.1 katalonc.sh -projectPath=/tmp/project -noSplash -testSuiteCollectionPath="Test Suites/New Test Suite Collection" -apiKey=${{ secrets.SECRET_KEY }} -browserType="Edge Chromium" --config -webui.autoUpdateDrivers=true -data /tmp/workspace
    
    - name: Get logs
      if: always()
      run: |
        ls /tmp/workspace
        cat /tmp/workspace/.metadata/.log

      
