name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install docker # Taken from https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
      run: |
        brew install docker
        colima start
        
    - name: Docker pull
      run: |
        docker image pull katalonstudio/katalon:test
        ls -al

    - name: Katalon Run 1
      run:  'docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon:test katalonc.sh -projectPath=/tmp/project -noSplash -testSuitePath="Test Suites/New Test Suite" -apiKey=${{ secrets.SECRET_KEY }} -browserType="Edge Chromium" --config -webui.autoUpdateDrivers=true'
