name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker pull
      run: |
        docker image pull katalonstudio/katalon:9.3.1

    - name: Katalon Run 1
      run:  'docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon:9.3.1 katalonc.sh -projectPath=/tmp/project -noSplash -testSuiteCollectionPath="Test Suites/New Test Suite Collection" -apiKey=${{ secrets.SECRET_KEY }} -browserType="Edge Chromium" --config -webui.autoUpdateDrivers=true'

    - name: Katalon Run 2
      run:  'docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon:9.3.1 katalonc.sh -projectPath=/tmp/project -noSplash -testSuiteCollectionPath="Test Suites/New Test Suite Collection" -apiKey=${{ secrets.SECRET_KEY }} -browserType="Edge Chromium" --config -webui.autoUpdateDrivers=true'

    - name: Katalon Run 3
      run:  'docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon:9.3.1 katalonc.sh -projectPath=/tmp/project -noSplash -testSuiteCollectionPath="Test Suites/New Test Suite Collection" -apiKey=${{ secrets.SECRET_KEY }} -browserType="Edge Chromium" --config -webui.autoUpdateDrivers=true'

    - name: Katalon Run 4
      run:  'docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon:9.3.1 katalonc.sh -projectPath=/tmp/project -noSplash -testSuiteCollectionPath="Test Suites/New Test Suite Collection" -apiKey=${{ secrets.SECRET_KEY }} -browserType="Edge Chromium" --config -webui.autoUpdateDrivers=true'

    - name: Katalon Run 5
      run:  'docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon:9.3.1 katalonc.sh -projectPath=/tmp/project -noSplash -testSuiteCollectionPath="Test Suites/New Test Suite Collection" -apiKey=${{ secrets.SECRET_KEY }} -browserType="Edge Chromium" --config -webui.autoUpdateDrivers=true'

    - name: Katalon Run 6
      run:  'docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon:9.3.1 katalonc.sh -projectPath=/tmp/project -noSplash -testSuiteCollectionPath="Test Suites/New Test Suite Collection" -apiKey=${{ secrets.SECRET_KEY }} -browserType="Edge Chromium" --config -webui.autoUpdateDrivers=true'

    - name: Katalon Run 7
      run:  'docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon:9.3.1 katalonc.sh -projectPath=/tmp/project -noSplash -testSuiteCollectionPath="Test Suites/New Test Suite Collection" -apiKey=${{ secrets.SECRET_KEY }} -browserType="Edge Chromium" --config -webui.autoUpdateDrivers=true'

    - name: Katalon Run 8
      run:  'docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon:9.3.1 katalonc.sh -projectPath=/tmp/project -noSplash -testSuiteCollectionPath="Test Suites/New Test Suite Collection" -apiKey=${{ secrets.SECRET_KEY }} -browserType="Edge Chromium" --config -webui.autoUpdateDrivers=true'

    - name: Katalon Run 9
      run:  'docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon:9.3.1 katalonc.sh -projectPath=/tmp/project -noSplash -testSuiteCollectionPath="Test Suites/New Test Suite Collection" -apiKey=${{ secrets.SECRET_KEY }} -browserType="Edge Chromium" --config -webui.autoUpdateDrivers=true'

    - name: Katalon Run 10
      run:  'docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon:9.3.1 katalonc.sh -projectPath=/tmp/project -noSplash -testSuiteCollectionPath="Test Suites/New Test Suite Collection" -apiKey=${{ secrets.SECRET_KEY }} -browserType="Edge Chromium" --config -webui.autoUpdateDrivers=true'

      
