name: Grunt
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install docker # Taken from https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
      run: |
        brew install docker
        colima start
        
    - name: Docker pull
      run: |
        docker image pull katalonstudio/katalon:9.3.1
        ls -al
